version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: dtmoney-web:latest
    restart: unless-stopped
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
