version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: belko-web
    expose:
      - 80
    restart: unless-stopped
    # depends_on:
    #   - server         # _opcional_ — isso só funciona se você usar um único compose com ambos services; se estiver em repos separados, ignore este depends_on
    networks:
      - belko_net

networks:
  belko_net:
    external: true
